### ISSUE TITLE
Switch 的 parse 有问题

### ISSUE THREAD

**Issue by Berrysoft** [Uni-Gal/Ayaka#24]
https://github.com/Uni-Gal/Ayaka/blob/c01f74587a641377ff81222d3974379837609390/utils/ayaka-script/src/line.rs#L46

Ayaka Script 允许 `|` 和 `||` 算符的存在，要么换一个算符，要么就要写一个复杂的 parser。

/cc @LaoshuBaby

**Comment by Berrysoft** [comment]
暂时认为应该换成 `@`，这是最简单的，通常也不会在文案中出现这个字符。

**Comment by LaoshuBaby** [comment]
还是换算符吧，毕竟需要写邮件地址的剧本应该不多见吧（笑

真要用@的时候就考虑用转义符号好了，类似`\{at}`的形式？
