### ISSUE TITLE
如何加载live2d的？

### ISSUE THREAD

**Issue by linonetwo** [Uni-Gal/Ayaka#345]
https://github.com/Uni-Gal/Ayaka/blob/master/plugins/live2d/src/lib.rs 里看起来没有用 live2d 相关的库

**Comment by Berrysoft** [comment]
Live2D 是前端配合插件处理的。看这里：https://github.com/Uni-Gal/Ayaka/blob/master/bins/ayaka-gui/src/components/Live2D.vue

**Comment by linonetwo** [comment]
了解了，都是靠 pixi-live2d-display ，我刚看到 https://github.com/OpenWebGAL/WebGAL 也是用这个。
